-- MySQL Script generated by MySQL Workbench
-- Sat Jul 25 00:18:06 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pdv
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pdv` ;

-- -----------------------------------------------------
-- Schema pdv
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pdv` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `pdv` ;

-- -----------------------------------------------------
-- Table `pdv`.`factory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pdv`.`factory` ;

CREATE TABLE IF NOT EXISTS `pdv`.`factory` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` TEXT NULL,
  `rfc` TEXT NULL,
  `estatus` TINYINT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pdv`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pdv`.`user` ;

CREATE TABLE IF NOT EXISTS `pdv`.`user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` TEXT NULL,
  `email` TEXT NULL,
  `password` TEXT NULL,
  `estatus` TINYINT NULL,
  `factory_id` BIGINT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_empresa_idx` (`factory_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_empresa`
    FOREIGN KEY (`factory_id`)
    REFERENCES `pdv`.`factory` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pdv`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pdv`.`role` ;

CREATE TABLE IF NOT EXISTS `pdv`.`role` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` TEXT NULL,
  `descripcion` TEXT NULL,
  `estatus` TINYINT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `pdv`.`user_has_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pdv`.`user_has_role` ;

CREATE TABLE IF NOT EXISTS `pdv`.`user_has_role` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `estatus` TINYINT NULL,
  `user_id` BIGINT NOT NULL,
  `role_id` BIGINT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_has_rol_usuario1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_usuario_has_rol_rol1_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_has_rol_usuario1`
    FOREIGN KEY (`user_id`)
    REFERENCES `pdv`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_rol_rol1`
    FOREIGN KEY (`role_id`)
    REFERENCES `pdv`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pdv`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pdv`.`customer` ;

CREATE TABLE IF NOT EXISTS `pdv`.`customer` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` TEXT NULL,
  `estatus` TINYINT NULL,
  `factory_id` BIGINT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cliente_empresa1_idx` (`factory_id` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_empresa1`
    FOREIGN KEY (`factory_id`)
    REFERENCES `pdv`.`factory` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pdv`.`contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pdv`.`contact` ;

CREATE TABLE IF NOT EXISTS `pdv`.`contact` (
  `id` BIGINT NOT NULL,
  `nombre` TEXT NULL,
  `valor` TEXT NULL,
  `estatus` TINYINT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pdv`.`customer_has_contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pdv`.`customer_has_contact` ;

CREATE TABLE IF NOT EXISTS `pdv`.`customer_has_contact` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `esatus` TINYINT NULL,
  `customer_id` BIGINT NOT NULL,
  `contact_id` BIGINT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cliente_has_contacto_cliente1_idx` (`customer_id` ASC) VISIBLE,
  INDEX `fk_cliente_has_contacto_contacto1_idx` (`contact_id` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_has_contacto_cliente1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `pdv`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_has_contacto_contacto1`
    FOREIGN KEY (`contact_id`)
    REFERENCES `pdv`.`contact` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pdv`.`factory_has_contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pdv`.`factory_has_contact` ;

CREATE TABLE IF NOT EXISTS `pdv`.`factory_has_contact` (
  `id` BIGINT NOT NULL,
  `estatus` TINYINT NULL,
  `factory_id` BIGINT NOT NULL,
  `contact_id` BIGINT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_empresa_has_contacto_empresa1_idx` (`factory_id` ASC) VISIBLE,
  INDEX `fk_empresa_has_contacto_contacto1_idx` (`contact_id` ASC) VISIBLE,
  CONSTRAINT `fk_empresa_has_contacto_empresa1`
    FOREIGN KEY (`factory_id`)
    REFERENCES `pdv`.`factory` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empresa_has_contacto_contacto1`
    FOREIGN KEY (`contact_id`)
    REFERENCES `pdv`.`contact` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pdv`.`user_has_contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pdv`.`user_has_contact` ;

CREATE TABLE IF NOT EXISTS `pdv`.`user_has_contact` (
  `id` BIGINT NOT NULL,
  `estatus` TINYINT NULL,
  `user_id` BIGINT NOT NULL,
  `contact_id` BIGINT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_has_contacto_usuario1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_usuario_has_contacto_contacto1_idx` (`contact_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_has_contacto_usuario1`
    FOREIGN KEY (`user_id`)
    REFERENCES `pdv`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_contacto_contacto1`
    FOREIGN KEY (`contact_id`)
    REFERENCES `pdv`.`contact` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '		2e';


-- -----------------------------------------------------
-- Table `pdv`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pdv`.`product` ;

CREATE TABLE IF NOT EXISTS `pdv`.`product` (
  `id` BIGINT NOT NULL,
  `nombre` TEXT NULL,
  `estatus` TINYINT NULL,
  `factory_id` BIGINT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_producto_empresa1_idx` (`factory_id` ASC) VISIBLE,
  CONSTRAINT `fk_producto_empresa1`
    FOREIGN KEY (`factory_id`)
    REFERENCES `pdv`.`factory` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pdv`.`presentation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pdv`.`presentation` ;

CREATE TABLE IF NOT EXISTS `pdv`.`presentation` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` TEXT NULL,
  `costo` FLOAT NULL,
  `precio_sin_impuestos` FLOAT NULL,
  `precio_con_impuestos` FLOAT NULL,
  `nombre_normalizado` TEXT NULL,
  `estatus` TINYINT NULL,
  `product_id` BIGINT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_presentacion_producto1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_presentacion_producto1`
    FOREIGN KEY (`product_id`)
    REFERENCES `pdv`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pdv`.`tax`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pdv`.`tax` ;

CREATE TABLE IF NOT EXISTS `pdv`.`tax` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` TEXT NULL,
  `descripcion` TEXT NULL,
  `valor` FLOAT NULL,
  `estatus` TINYINT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pdv`.`product_has_tax`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pdv`.`product_has_tax` ;

CREATE TABLE IF NOT EXISTS `pdv`.`product_has_tax` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `estatus` TINYINT NULL,
  `product_id` BIGINT NOT NULL,
  `tax_id` BIGINT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_producto_has_impuesto_producto1_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_producto_has_impuesto_impuestos1_idx` (`tax_id` ASC) VISIBLE,
  CONSTRAINT `fk_producto_has_impuesto_producto1`
    FOREIGN KEY (`product_id`)
    REFERENCES `pdv`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_has_impuesto_impuestos1`
    FOREIGN KEY (`tax_id`)
    REFERENCES `pdv`.`tax` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pdv`.`sell`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pdv`.`sell` ;

CREATE TABLE IF NOT EXISTS `pdv`.`sell` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `folio` BIGINT NULL,
  `total_letra` TEXT NULL,
  `folio_verificador` TEXT NULL,
  `customer_id` BIGINT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_venta_cliente1_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_venta_cliente1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `pdv`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pdv`.`sell_detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pdv`.`sell_detail` ;

CREATE TABLE IF NOT EXISTS `pdv`.`sell_detail` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `cantidad` FLOAT NULL,
  `descripcion` TEXT NULL,
  `precio` FLOAT NULL,
  `importe` FLOAT NULL,
  `estatus` TINYINT NULL,
  `sell_id` BIGINT NOT NULL,
  `presentation_id` BIGINT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_venta_detalle_venta1_idx` (`sell_id` ASC) VISIBLE,
  INDEX `fk_venta_detalle_presentacion1_idx` (`presentation_id` ASC) VISIBLE,
  CONSTRAINT `fk_venta_detalle_venta1`
    FOREIGN KEY (`sell_id`)
    REFERENCES `pdv`.`sell` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venta_detalle_presentacion1`
    FOREIGN KEY (`presentation_id`)
    REFERENCES `pdv`.`presentation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
