/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.mor.chineloio.view;

import java.awt.Image;
import java.awt.Toolkit;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import mx.marcoabm.sinv.action.Action;
import mx.marcoabm.sinv.entity.Product;
import mx.marcoabm.sinv.entity.Sale;
import mx.marcoabm.sinv.utils.img.PathResources;

/**
 *
 * @author MARCOABM
 */
public class Main extends javax.swing.JFrame {

    Integer lastX;
    Integer lastY;
    Action ac = new Action();

    /**
     * Creates new form main
     */
    public Main() throws URISyntaxException {
        initComponents();

        this.setIconImage(Toolkit.getDefaultToolkit().getImage(new PathResources().getLogo()));

        tabSearchSell.setVisible(false);
        jScrollPane3.setVisible(false);
        this.styleTables();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        titleMain = new javax.swing.JLabel();
        titleSells = new javax.swing.JLabel();
        btnDoSell = new javax.swing.JLabel();
        btnSearchSell = new javax.swing.JLabel();
        btnTestSellSell = new javax.swing.JLabel();
        btnCustomersSell = new javax.swing.JLabel();
        btnDownloadsSell = new javax.swing.JLabel();
        titleStock = new javax.swing.JLabel();
        btnProductsStock = new javax.swing.JLabel();
        titleConfig = new javax.swing.JLabel();
        btnSincronizeConfig = new javax.swing.JLabel();
        btnAjustConfig = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        panelDoSell = new javax.swing.JPanel();
        titleArticuloSell = new javax.swing.JLabel();
        inputSearchItemSell = new javax.swing.JTextField();
        titleCustomerSell = new javax.swing.JLabel();
        inputSearchCustomerSell = new javax.swing.JTextField();
        titleTotalSell = new javax.swing.JLabel();
        titleTotalValueSell = new javax.swing.JLabel();
        btnCancelSell = new javax.swing.JLabel();
        btnAjustConfig2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabItemCustomerSell = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabItemsSell = new javax.swing.JTable();
        panelSearchSell = new javax.swing.JPanel();
        titleFirstSearchSell = new javax.swing.JLabel();
        dateFirstSearchSell = new com.toedter.calendar.JDateChooser();
        dateFirstSearchSell1 = new com.toedter.calendar.JDateChooser();
        inputSearchSell = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabSearchSell = new javax.swing.JTable();
        titleAuxSearchSell1 = new javax.swing.JLabel();
        titleAuxSearchSell2 = new javax.swing.JLabel();
        titleDateEndSearchSell1 = new javax.swing.JLabel();
        titleSearchSell = new javax.swing.JLabel();
        btnSearchSearchSell = new javax.swing.JLabel();
        btnExportExcelSearchSell = new javax.swing.JLabel();
        btnExportPDFSearchSell = new javax.swing.JLabel();
        panelCustomer = new javax.swing.JPanel();
        inputEmailCustomer = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabCustomer = new javax.swing.JTable();
        titleEmailCustomer = new javax.swing.JLabel();
        titleNameCustomer = new javax.swing.JLabel();
        inputNameCustomer = new javax.swing.JTextField();
        btnAddCustomer = new javax.swing.JLabel();
        panelProducts = new javax.swing.JPanel();
        titleArticuloSell1 = new javax.swing.JLabel();
        inputSearchItemSell1 = new javax.swing.JTextField();
        titleCustomerSell1 = new javax.swing.JLabel();
        inputSearchCustomerSell1 = new javax.swing.JTextField();
        btnCancelSell1 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabItemCustomerSell1 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabItemsSell1 = new javax.swing.JTable();
        titleArticuloSell2 = new javax.swing.JLabel();
        titleArticuloSell3 = new javax.swing.JLabel();
        inputSearchCustomerSell2 = new javax.swing.JTextField();
        btnCancelSell2 = new javax.swing.JLabel();
        titleCustomerSell2 = new javax.swing.JLabel();
        titleWebSite = new javax.swing.JLabel();

        jMenuItem4.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem4.setText("Vender");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jPopupMenu2.add(jMenuItem4);

        jMenuItem1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem1.setText("Modificar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu2.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem2.setText("Quitar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu2.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem3.setText("Modificar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem3);

        jMenuItem5.setBackground(new java.awt.Color(255, 0, 0));
        jMenuItem5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem5.setText("Quitar");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem5);

        jMenuItem6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem6.setText("Descargar");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jPopupMenu3.add(jMenuItem6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(842, 536));
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(246, 246, 246));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        titleMain.setBackground(new java.awt.Color(0, 0, 0));
        titleMain.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        titleMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleMain.setText("Panel de Navegación");
        jPanel1.add(titleMain);
        titleMain.setBounds(0, 0, 170, 30);

        titleSells.setBackground(new java.awt.Color(0, 0, 0));
        titleSells.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        titleSells.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titleSells.setText(" Ventas");
        titleSells.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel1.add(titleSells);
        titleSells.setBounds(0, 50, 170, 17);

        btnDoSell.setBackground(new java.awt.Color(204, 204, 204));
        btnDoSell.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDoSell.setForeground(new java.awt.Color(255, 255, 255));
        btnDoSell.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDoSell.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/mor/chineloio/utils/btnVender.png"))); // NOI18N
        btnDoSell.setText("Realizar Nota");
        btnDoSell.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(btnDoSell);
        btnDoSell.setBounds(0, 70, 170, 35);
        btnDoSell.getAccessibleContext().setAccessibleName("");

        btnSearchSell.setBackground(new java.awt.Color(204, 204, 204));
        btnSearchSell.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSearchSell.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchSell.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSearchSell.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/mor/chineloio/utils/btnHistorial.png"))); // NOI18N
        btnSearchSell.setText("Realizar Nota");
        btnSearchSell.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(btnSearchSell);
        btnSearchSell.setBounds(0, 110, 170, 35);
        btnSearchSell.getAccessibleContext().setAccessibleName("");
        btnSearchSell.getAccessibleContext().setAccessibleDescription("");

        btnTestSellSell.setBackground(new java.awt.Color(204, 204, 204));
        btnTestSellSell.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnTestSellSell.setForeground(new java.awt.Color(255, 255, 255));
        btnTestSellSell.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTestSellSell.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/mor/chineloio/utils/btnCotizacion.png"))); // NOI18N
        btnTestSellSell.setText("Realizar Nota");
        btnTestSellSell.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(btnTestSellSell);
        btnTestSellSell.setBounds(0, 150, 170, 35);
        btnTestSellSell.getAccessibleContext().setAccessibleName("");

        btnCustomersSell.setBackground(new java.awt.Color(204, 204, 204));
        btnCustomersSell.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCustomersSell.setForeground(new java.awt.Color(255, 255, 255));
        btnCustomersSell.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCustomersSell.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/mor/chineloio/utils/btnClientes.png"))); // NOI18N
        btnCustomersSell.setText("Realizar Nota");
        btnCustomersSell.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(btnCustomersSell);
        btnCustomersSell.setBounds(0, 190, 170, 35);
        btnCustomersSell.getAccessibleContext().setAccessibleName("");

        btnDownloadsSell.setBackground(new java.awt.Color(204, 204, 204));
        btnDownloadsSell.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDownloadsSell.setForeground(new java.awt.Color(255, 255, 255));
        btnDownloadsSell.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDownloadsSell.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/mor/chineloio/utils/btnDescargas.png"))); // NOI18N
        btnDownloadsSell.setText("Realizar Nota");
        btnDownloadsSell.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(btnDownloadsSell);
        btnDownloadsSell.setBounds(0, 230, 170, 35);
        btnDownloadsSell.getAccessibleContext().setAccessibleName("");

        titleStock.setBackground(new java.awt.Color(0, 0, 0));
        titleStock.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        titleStock.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titleStock.setText(" Inventario");
        titleStock.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel1.add(titleStock);
        titleStock.setBounds(0, 280, 170, 17);

        btnProductsStock.setBackground(new java.awt.Color(204, 204, 204));
        btnProductsStock.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnProductsStock.setForeground(new java.awt.Color(255, 255, 255));
        btnProductsStock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnProductsStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/mor/chineloio/utils/btnProductos.png"))); // NOI18N
        btnProductsStock.setText("Realizar Nota");
        btnProductsStock.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(btnProductsStock);
        btnProductsStock.setBounds(0, 300, 170, 35);
        btnProductsStock.getAccessibleContext().setAccessibleName("");

        titleConfig.setBackground(new java.awt.Color(0, 0, 0));
        titleConfig.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        titleConfig.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titleConfig.setText("Configuración");
        titleConfig.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel1.add(titleConfig);
        titleConfig.setBounds(0, 350, 170, 17);

        btnSincronizeConfig.setBackground(new java.awt.Color(204, 204, 204));
        btnSincronizeConfig.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSincronizeConfig.setForeground(new java.awt.Color(255, 255, 255));
        btnSincronizeConfig.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSincronizeConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/mor/chineloio/utils/btnSincronizar.png"))); // NOI18N
        btnSincronizeConfig.setText("Realizar Nota");
        btnSincronizeConfig.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(btnSincronizeConfig);
        btnSincronizeConfig.setBounds(0, 370, 170, 35);
        btnSincronizeConfig.getAccessibleContext().setAccessibleName("");

        btnAjustConfig.setBackground(new java.awt.Color(204, 204, 204));
        btnAjustConfig.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAjustConfig.setForeground(new java.awt.Color(255, 255, 255));
        btnAjustConfig.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAjustConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/mor/chineloio/utils/btnAjustes.png"))); // NOI18N
        btnAjustConfig.setText("Realizar Nota");
        btnAjustConfig.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(btnAjustConfig);
        btnAjustConfig.setBounds(0, 410, 170, 35);
        btnAjustConfig.getAccessibleContext().setAccessibleName("");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/marcoabm/sinv/utils/img/ic_exit.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        jPanel1.add(jLabel1);
        jLabel1.setBounds(812, 0, 0, 0);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/marcoabm/sinv/utils/img/ic_minimize.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(780, 0, 0, 0);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/marcoabm/sinv/utils/img/ic_files.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 360, 120, 120);

        panelDoSell.setBackground(new java.awt.Color(246, 246, 246));
        panelDoSell.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelDoSell.setLayout(null);

        titleArticuloSell.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        titleArticuloSell.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titleArticuloSell.setText("Artículo");
        panelDoSell.add(titleArticuloSell);
        titleArticuloSell.setBounds(20, 10, 149, 17);

        inputSearchItemSell.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        inputSearchItemSell.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputSearchItemSellKeyReleased(evt);
            }
        });
        panelDoSell.add(inputSearchItemSell);
        inputSearchItemSell.setBounds(20, 30, 340, 30);

        titleCustomerSell.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        titleCustomerSell.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titleCustomerSell.setText("Cliente");
        panelDoSell.add(titleCustomerSell);
        titleCustomerSell.setBounds(370, 10, 149, 17);

        inputSearchCustomerSell.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        inputSearchCustomerSell.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputSearchCustomerSellKeyReleased(evt);
            }
        });
        panelDoSell.add(inputSearchCustomerSell);
        inputSearchCustomerSell.setBounds(370, 30, 340, 30);

        titleTotalSell.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        titleTotalSell.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleTotalSell.setText("Total $");
        panelDoSell.add(titleTotalSell);
        titleTotalSell.setBounds(20, 280, 70, 22);

        titleTotalValueSell.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        titleTotalValueSell.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titleTotalValueSell.setText("00.00");
        panelDoSell.add(titleTotalValueSell);
        titleTotalValueSell.setBounds(90, 280, 120, 22);

        btnCancelSell.setBackground(new java.awt.Color(204, 204, 204));
        btnCancelSell.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCancelSell.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelSell.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCancelSell.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/mor/chineloio/utils/btnCancelar.png"))); // NOI18N
        btnCancelSell.setText("Realizar Nota");
        btnCancelSell.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelDoSell.add(btnCancelSell);
        btnCancelSell.setBounds(540, 270, 170, 35);
        btnCancelSell.getAccessibleContext().setAccessibleName("");

        btnAjustConfig2.setBackground(new java.awt.Color(204, 204, 204));
        btnAjustConfig2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAjustConfig2.setForeground(new java.awt.Color(255, 255, 255));
        btnAjustConfig2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAjustConfig2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/mor/chineloio/utils/btnImprimir.png"))); // NOI18N
        btnAjustConfig2.setText("Realizar Nota");
        btnAjustConfig2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelDoSell.add(btnAjustConfig2);
        btnAjustConfig2.setBounds(350, 270, 170, 35);
        btnAjustConfig2.getAccessibleContext().setAccessibleName("");

        tabItemCustomerSell.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        tabItemCustomerSell.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        tabItemCustomerSell.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabItemCustomerSell.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        tabItemCustomerSell.setComponentPopupMenu(jPopupMenu2);
        tabItemCustomerSell.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabItemCustomerSell.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabItemCustomerSell);

        panelDoSell.add(jScrollPane1);
        jScrollPane1.setBounds(20, 70, 690, 190);

        tabItemsSell.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        tabItemsSell.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cant.", "Descripción", "Precio", "Importe"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabItemsSell.setComponentPopupMenu(jPopupMenu1);
        tabItemsSell.setRowSelectionAllowed(false);
        tabItemsSell.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(tabItemsSell);
        if (tabItemsSell.getColumnModel().getColumnCount() > 0) {
            tabItemsSell.getColumnModel().getColumn(0).setHeaderValue("Cant.");
            tabItemsSell.getColumnModel().getColumn(1).setResizable(false);
            tabItemsSell.getColumnModel().getColumn(1).setHeaderValue("Descripción");
            tabItemsSell.getColumnModel().getColumn(2).setHeaderValue("Precio");
            tabItemsSell.getColumnModel().getColumn(3).setHeaderValue("Importe");
        }

        panelDoSell.add(jScrollPane2);
        jScrollPane2.setBounds(20, 310, 690, 350);

        jPanel1.add(panelDoSell);
        panelDoSell.setBounds(170, 0, 730, 680);

        panelSearchSell.setBackground(new java.awt.Color(246, 246, 246));
        panelSearchSell.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelSearchSell.setMaximumSize(new java.awt.Dimension(730, 680));
        panelSearchSell.setMinimumSize(new java.awt.Dimension(730, 680));
        panelSearchSell.setPreferredSize(new java.awt.Dimension(730, 680));
        panelSearchSell.setLayout(null);

        titleFirstSearchSell.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        titleFirstSearchSell.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titleFirstSearchSell.setText("Fecha Inicio");
        panelSearchSell.add(titleFirstSearchSell);
        titleFirstSearchSell.setBounds(20, 20, 90, 17);
        panelSearchSell.add(dateFirstSearchSell);
        dateFirstSearchSell.setBounds(50, 40, 120, 30);
        panelSearchSell.add(dateFirstSearchSell1);
        dateFirstSearchSell1.setBounds(200, 40, 120, 30);

        inputSearchSell.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        inputSearchSell.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputSearchSellKeyReleased(evt);
            }
        });
        panelSearchSell.add(inputSearchSell);
        inputSearchSell.setBounds(340, 40, 190, 30);

        tabSearchSell.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        tabSearchSell.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabSearchSell.setComponentPopupMenu(jPopupMenu3);
        tabSearchSell.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tabSearchSell);

        panelSearchSell.add(jScrollPane3);
        jScrollPane3.setBounds(20, 80, 690, 540);

        titleAuxSearchSell1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        titleAuxSearchSell1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titleAuxSearchSell1.setText("Del");
        panelSearchSell.add(titleAuxSearchSell1);
        titleAuxSearchSell1.setBounds(20, 50, 30, 17);

        titleAuxSearchSell2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        titleAuxSearchSell2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titleAuxSearchSell2.setText("Al");
        panelSearchSell.add(titleAuxSearchSell2);
        titleAuxSearchSell2.setBounds(180, 50, 30, 17);

        titleDateEndSearchSell1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        titleDateEndSearchSell1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titleDateEndSearchSell1.setText("Fecha Final");
        panelSearchSell.add(titleDateEndSearchSell1);
        titleDateEndSearchSell1.setBounds(200, 20, 80, 17);

        titleSearchSell.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        titleSearchSell.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titleSearchSell.setText("Buscar");
        panelSearchSell.add(titleSearchSell);
        titleSearchSell.setBounds(340, 20, 80, 17);

        btnSearchSearchSell.setBackground(new java.awt.Color(204, 204, 204));
        btnSearchSearchSell.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSearchSearchSell.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchSearchSell.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSearchSearchSell.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/mor/chineloio/utils/btnBuscar.png"))); // NOI18N
        btnSearchSearchSell.setText("Realizar Nota");
        btnSearchSearchSell.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelSearchSell.add(btnSearchSearchSell);
        btnSearchSearchSell.setBounds(540, 40, 170, 35);

        btnExportExcelSearchSell.setBackground(new java.awt.Color(204, 204, 204));
        btnExportExcelSearchSell.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnExportExcelSearchSell.setForeground(new java.awt.Color(255, 255, 255));
        btnExportExcelSearchSell.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExportExcelSearchSell.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/mor/chineloio/utils/btnExportarPDF.png"))); // NOI18N
        btnExportExcelSearchSell.setText("Realizar Nota");
        btnExportExcelSearchSell.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelSearchSell.add(btnExportExcelSearchSell);
        btnExportExcelSearchSell.setBounds(20, 630, 170, 35);

        btnExportPDFSearchSell.setBackground(new java.awt.Color(204, 204, 204));
        btnExportPDFSearchSell.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnExportPDFSearchSell.setForeground(new java.awt.Color(255, 255, 255));
        btnExportPDFSearchSell.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExportPDFSearchSell.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/mor/chineloio/utils/btnExportarExcel.png"))); // NOI18N
        btnExportPDFSearchSell.setText("Realizar Nota");
        btnExportPDFSearchSell.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelSearchSell.add(btnExportPDFSearchSell);
        btnExportPDFSearchSell.setBounds(540, 630, 170, 35);

        jPanel1.add(panelSearchSell);
        panelSearchSell.setBounds(170, 0, 730, 680);

        panelCustomer.setBackground(new java.awt.Color(246, 246, 246));
        panelCustomer.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelCustomer.setMaximumSize(new java.awt.Dimension(730, 680));
        panelCustomer.setMinimumSize(new java.awt.Dimension(730, 680));
        panelCustomer.setLayout(null);

        inputEmailCustomer.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        inputEmailCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEmailCustomerActionPerformed(evt);
            }
        });
        inputEmailCustomer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputEmailCustomerKeyReleased(evt);
            }
        });
        panelCustomer.add(inputEmailCustomer);
        inputEmailCustomer.setBounds(300, 40, 230, 30);

        tabCustomer.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        tabCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabCustomer.setComponentPopupMenu(jPopupMenu3);
        tabCustomer.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(tabCustomer);

        panelCustomer.add(jScrollPane4);
        jScrollPane4.setBounds(20, 80, 690, 580);

        titleEmailCustomer.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        titleEmailCustomer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titleEmailCustomer.setText("Email");
        panelCustomer.add(titleEmailCustomer);
        titleEmailCustomer.setBounds(300, 20, 80, 17);

        titleNameCustomer.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        titleNameCustomer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titleNameCustomer.setText("Nombre");
        panelCustomer.add(titleNameCustomer);
        titleNameCustomer.setBounds(20, 20, 80, 17);

        inputNameCustomer.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        inputNameCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNameCustomerActionPerformed(evt);
            }
        });
        inputNameCustomer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputNameCustomerKeyReleased(evt);
            }
        });
        panelCustomer.add(inputNameCustomer);
        inputNameCustomer.setBounds(20, 40, 270, 30);

        btnAddCustomer.setBackground(new java.awt.Color(204, 204, 204));
        btnAddCustomer.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAddCustomer.setForeground(new java.awt.Color(255, 255, 255));
        btnAddCustomer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAddCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/mor/chineloio/utils/btnAgregar.png"))); // NOI18N
        btnAddCustomer.setText("Realizar Nota");
        btnAddCustomer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelCustomer.add(btnAddCustomer);
        btnAddCustomer.setBounds(540, 40, 170, 35);

        jPanel1.add(panelCustomer);
        panelCustomer.setBounds(170, 0, 730, 680);

        panelProducts.setBackground(new java.awt.Color(246, 246, 246));
        panelProducts.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelProducts.setLayout(null);

        titleArticuloSell1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        titleArticuloSell1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleArticuloSell1.setText("Presentaciones");
        panelProducts.add(titleArticuloSell1);
        titleArticuloSell1.setBounds(20, 620, 690, 17);

        inputSearchItemSell1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        inputSearchItemSell1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputSearchItemSell1KeyReleased(evt);
            }
        });
        panelProducts.add(inputSearchItemSell1);
        inputSearchItemSell1.setBounds(20, 30, 510, 30);

        titleCustomerSell1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        titleCustomerSell1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titleCustomerSell1.setText("Costo");
        panelProducts.add(titleCustomerSell1);
        titleCustomerSell1.setBounds(330, 310, 149, 17);

        inputSearchCustomerSell1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        inputSearchCustomerSell1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputSearchCustomerSell1KeyReleased(evt);
            }
        });
        panelProducts.add(inputSearchCustomerSell1);
        inputSearchCustomerSell1.setBounds(330, 330, 190, 30);

        btnCancelSell1.setBackground(new java.awt.Color(204, 204, 204));
        btnCancelSell1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCancelSell1.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelSell1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCancelSell1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/mor/chineloio/utils/btnAgregar.png"))); // NOI18N
        btnCancelSell1.setText("Realizar Nota");
        btnCancelSell1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelProducts.add(btnCancelSell1);
        btnCancelSell1.setBounds(540, 325, 170, 35);

        tabItemCustomerSell1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        tabItemCustomerSell1.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        tabItemCustomerSell1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabItemCustomerSell1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        tabItemCustomerSell1.setComponentPopupMenu(jPopupMenu2);
        tabItemCustomerSell1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabItemCustomerSell1.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(tabItemCustomerSell1);

        panelProducts.add(jScrollPane5);
        jScrollPane5.setBounds(20, 70, 690, 180);

        tabItemsSell1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        tabItemsSell1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabItemsSell1.setComponentPopupMenu(jPopupMenu1);
        tabItemsSell1.setRowSelectionAllowed(false);
        tabItemsSell1.setSelectionMode();
        jScrollPane6.setViewportView(tabItemsSell1);

        panelProducts.add(jScrollPane6);
        jScrollPane6.setBounds(20, 370, 690, 250);

        titleArticuloSell2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        titleArticuloSell2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titleArticuloSell2.setText("Artículo");
        panelProducts.add(titleArticuloSell2);
        titleArticuloSell2.setBounds(20, 10, 149, 17);

        titleArticuloSell3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        titleArticuloSell3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleArticuloSell3.setText("Productos");
        panelProducts.add(titleArticuloSell3);
        titleArticuloSell3.setBounds(20, 250, 690, 17);

        inputSearchCustomerSell2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        inputSearchCustomerSell2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputSearchCustomerSell2KeyReleased(evt);
            }
        });
        panelProducts.add(inputSearchCustomerSell2);
        inputSearchCustomerSell2.setBounds(20, 330, 300, 30);

        btnCancelSell2.setBackground(new java.awt.Color(204, 204, 204));
        btnCancelSell2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCancelSell2.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelSell2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCancelSell2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/mor/chineloio/utils/btnAgregar.png"))); // NOI18N
        btnCancelSell2.setText("Realizar Nota");
        btnCancelSell2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelProducts.add(btnCancelSell2);
        btnCancelSell2.setBounds(540, 27, 170, 35);

        titleCustomerSell2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        titleCustomerSell2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titleCustomerSell2.setText("Nombre");
        panelProducts.add(titleCustomerSell2);
        titleCustomerSell2.setBounds(20, 310, 149, 17);

        jPanel1.add(panelProducts);
        panelProducts.setBounds(170, 0, 730, 680);

        titleWebSite.setBackground(new java.awt.Color(0, 0, 0));
        titleWebSite.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        titleWebSite.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleWebSite.setText("www.chinelo.io");
        jPanel1.add(titleWebSite);
        titleWebSite.setBounds(0, 660, 170, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        Integer msgExit = JOptionPane.showConfirmDialog(Main.this, "¿Realmente quiere salir de la aplicación?", "Advertencia", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (msgExit == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_jLabel2MousePressed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        lastX = evt.getXOnScreen();
        lastY = evt.getYOnScreen();
     }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        // Move frame by the mouse delta
        setLocation(getLocationOnScreen().x + x - lastX,
                getLocationOnScreen().y + y - lastY);
        lastX = x;
        lastY = y;
    }//GEN-LAST:event_formMouseDragged

    private void inputSearchItemSellKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputSearchItemSellKeyReleased
        //Llenar tabla de elementos
        tabItemCustomerSell.setModel(ac.findAllByName(inputSearchItemSell.getText().toUpperCase()));
        tabItemCustomerSell.getColumnModel().getColumn(0).setMaxWidth(0);
        tabItemCustomerSell.getColumnModel().getColumn(0).setMinWidth(0);
        tabItemCustomerSell.getColumnModel().getColumn(0).setPreferredWidth(0);
        //Dimensiones de la columna 1 que es nombre
        tabItemCustomerSell.getColumnModel().getColumn(1).setPreferredWidth(250);
        tabItemCustomerSell.getColumnModel().getColumn(1).setPreferredWidth(250);
        tabItemCustomerSell.getColumnModel().getColumn(1).setPreferredWidth(250);
        tabItemCustomerSell.getTableHeader().setReorderingAllowed(false);
        //Desabilitar la ediciòn de las celdas
        tabItemCustomerSell.setDefaultEditor(Object.class, null);
        //Modo de seleccion de celdas
        tabItemCustomerSell.setSelectionMode(2);
        tabItemCustomerSell.setRowSelectionAllowed(true);
        tabItemCustomerSell.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }//GEN-LAST:event_inputSearchItemSellKeyReleased

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        if (tabItemCustomerSell.getSelectedRow() != -1) {
            Product product = ac.selectSpecificProduct(tabItemCustomerSell, tabItemCustomerSell.getSelectedRow());
            Boolean sameProduct = ac.findProudctIntoTabSale(tabItemsSell, product);
            if (sameProduct) {
                JOptionPane.showMessageDialog(null, "El producto ya esta en la nota", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            } else {
                SpinnerNumberModel sModel = new SpinnerNumberModel(1, 1, 999999999, 1);
                JSpinner spinner = new JSpinner(sModel);
                Integer askQuantity = JOptionPane.showOptionDialog(null, spinner, "¿Cuantas piezas son?", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
                if (askQuantity == JOptionPane.OK_OPTION) {
                    String price = ac.priceStringToBigDecimal(product.getPrice());
                    String importPrice = new BigDecimal(price).multiply(new BigDecimal(spinner.getValue().toString())).toPlainString();
                    ac.addProductoTable(Integer.parseInt(spinner.getValue().toString()), product.getName(), product.getPrice(), importPrice, tabItemsSell, titleTotalValueSell);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un producto", "Aviso", JOptionPane.YES_OPTION);
        }
     }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Product product = ac.selectSpecificProduct(tabItemCustomerSell, tabItemCustomerSell.getSelectedRow());
        if (product.getId() != 0) {
            jTextField1.setText(product.getName());
            jTextField3.setText(product.getPrice());
            jLabel16.setVisible(true);
            jLabel20.setVisible(true);
            jLabel18.setVisible(false);
            jLabel19.setVisible(false);
            jLabel19.setName(product.getId().toString());
            jSpinner1.setVisible(false);

        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un Producto", "Aviso", JOptionPane.YES_OPTION);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Product product = ac.selectSpecificProduct(tabItemCustomerSell, tabItemCustomerSell.getSelectedRow());
        if (product.getId() != 0) {
            Object[] optionsRemove = {"Aceptar", "No"};
            int caseRemove = JOptionPane.showOptionDialog(
                    null,
                    "¿Desea borrar el producto " + product.getName() + "?",
                    "Advertencia",
                    JOptionPane.YES_NO_CANCEL_OPTION,
                    JOptionPane.PLAIN_MESSAGE,
                    null,
                    optionsRemove,
                    null
            );
            if (caseRemove == 0) {
                if (ac.delete(product).getId() != 0) {
                    JOptionPane.showMessageDialog(null, "Producto borrado correctamente", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                    tabItemCustomerSell.setModel(ac.findAll());
                    this.styleTables();
                } else {
                    JOptionPane.showMessageDialog(null, "Ocurrio un erro al borrar el producto", "Aviso", JOptionPane.YES_OPTION);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un Producto", "Aviso", JOptionPane.YES_OPTION);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        if (tabItemsSell.getSelectedRow() != -1) {
            Object[] optionsRemove = {"Aceptar", "No"};
            int caseRemove = JOptionPane.showOptionDialog(
                    null,
                    "¿Desea quitar "
                    + tabItemsSell.getValueAt(tabItemsSell.getSelectedRow(), 1).toString()
                    + " la nota?",
                    "Advertencia",
                    JOptionPane.YES_NO_CANCEL_OPTION,
                    JOptionPane.PLAIN_MESSAGE,
                    null,
                    optionsRemove,
                    null
            );
            if (caseRemove != 1) {
                String importProduct = tabItemsSell.getValueAt(tabItemsSell.getSelectedRow(), 3).toString();
                String total = ac.priceStringToBigDecimal(titleTotalValueSell.getText());
                DefaultTableModel model = (DefaultTableModel) tabItemsSell.getModel();
                model.removeRow(tabItemsSell.getSelectedRow());
                tabItemsSell.setModel(model);
                titleTotalValueSell.setText(new BigDecimal(total).subtract(new BigDecimal(importProduct)).setScale(2, RoundingMode.HALF_UP).toPlainString());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un producto de la nota", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        if (tabItemsSell.getSelectedRow() != -1) {
            String priceProduct = tabItemsSell.getValueAt(tabItemsSell.getSelectedRow(), 2).toString();
            String importProduct = tabItemsSell.getValueAt(tabItemsSell.getSelectedRow(), 3).toString();
            String totalTemp = titleTotalValueSell.getText();
            String totalRest = new BigDecimal(titleTotalValueSell.getText()).subtract(new BigDecimal(importProduct)).setScale(2, RoundingMode.HALF_UP).toPlainString();

            SpinnerNumberModel sModel = new SpinnerNumberModel(1, 1, 999999999, 1);
            JSpinner spinner = new JSpinner(sModel);
            spinner.setValue(Integer.parseInt(tabItemsSell.getValueAt(tabItemsSell.getSelectedRow(), 0).toString()));
            Integer askQuantity = JOptionPane.showOptionDialog(null, spinner, "¿Cuantas piezas son?", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
            if (askQuantity == JOptionPane.OK_OPTION) {
                String newImport = new BigDecimal(priceProduct).multiply(new BigDecimal(spinner.getValue().toString())).toPlainString();
                String totalNew = new BigDecimal(totalRest).add(new BigDecimal(newImport)).toPlainString();
                titleTotalValueSell.setText(totalNew);
                tabItemsSell.setValueAt(spinner.getValue(), tabItemsSell.getSelectedRow(), 0);
                tabItemsSell.setValueAt(newImport, tabItemsSell.getSelectedRow(), 3);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un producto de la nota", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
        ac.openFileNote();
    }//GEN-LAST:event_jLabel8MousePressed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        if (tabSearchSell.getSelectedRow() != -1) {
            ac.buildReport(Integer.parseInt(tabSearchSell.getValueAt(tabSearchSell.getSelectedRow(), 1).toString()));
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una nota a descargar", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void inputSearchCustomerSellKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputSearchCustomerSellKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSearchCustomerSellKeyReleased

    private void inputSearchSellKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputSearchSellKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSearchSellKeyReleased

    private void inputEmailCustomerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputEmailCustomerKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEmailCustomerKeyReleased

    private void inputEmailCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEmailCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEmailCustomerActionPerformed

    private void inputNameCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNameCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNameCustomerActionPerformed

    private void inputNameCustomerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputNameCustomerKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNameCustomerKeyReleased

    private void inputSearchItemSell1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputSearchItemSell1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSearchItemSell1KeyReleased

    private void inputSearchCustomerSell1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputSearchCustomerSell1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSearchCustomerSell1KeyReleased

    private void inputSearchCustomerSell2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputSearchCustomerSell2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSearchCustomerSell2KeyReleased

    private void styleTables() {
        //Llenar tabla de elementos
        tabItemCustomerSell.setModel(ac.findAll());
        //Ocultar columna del ID, de la tabla1/jTable1/tableProducto
        tabItemCustomerSell.getColumnModel().getColumn(0).setMaxWidth(0);
        tabItemCustomerSell.getColumnModel().getColumn(0).setMinWidth(0);
        tabItemCustomerSell.getColumnModel().getColumn(0).setPreferredWidth(0);
        //Dimensiones de la columna 1 que es nombre
        tabItemCustomerSell.getColumnModel().getColumn(1).setPreferredWidth(250);
        tabItemCustomerSell.getColumnModel().getColumn(1).setPreferredWidth(250);
        tabItemCustomerSell.getColumnModel().getColumn(1).setPreferredWidth(250);
        tabItemCustomerSell.getTableHeader().setReorderingAllowed(false);
        //Desabilitar la ediciòn de las celdas
        tabItemCustomerSell.setDefaultEditor(Object.class, null);
        //Modo de seleccion de celdas
        tabItemCustomerSell.setSelectionMode(2);
        tabItemCustomerSell.setRowSelectionAllowed(true);
        tabItemCustomerSell.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        //Dimensiones de la tabla de Nota, columnas
        tabItemsSell.getColumnModel().getColumn(0).setPreferredWidth(10);
        tabItemsSell.getColumnModel().getColumn(1).setPreferredWidth(330);
        tabItemsSell.getColumnModel().getColumn(2).setPreferredWidth(30);
        tabItemsSell.getColumnModel().getColumn(3).setPreferredWidth(30);
        tabItemsSell.getTableHeader().setReorderingAllowed(false);
        tabItemsSell.setRowSelectionAllowed(true);
        tabItemsSell.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        //Table3 Historial
        tabSearchSell.getTableHeader().setReorderingAllowed(false);
        tabSearchSell.getColumnModel().getColumn(0).setPreferredWidth(100);
        tabSearchSell.getColumnModel().getColumn(1).setPreferredWidth(80);
        tabSearchSell.getColumnModel().getColumn(2).setPreferredWidth(350);
        tabSearchSell.getColumnModel().getColumn(3).setPreferredWidth(130);
        tabSearchSell.setDefaultEditor(Object.class, null);
        tabSearchSell.getTableHeader().setReorderingAllowed(false);
        //Modo de seleccion de celdas
        tabSearchSell.setSelectionMode(2);
        tabSearchSell.setRowSelectionAllowed(true);
        tabSearchSell.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        //Ocultar botones de modificar-cancelar
        jLabel16.setVisible(false);
        jLabel20.setVisible(false);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Main().setVisible(true);
                } catch (URISyntaxException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAddCustomer;
    private javax.swing.JLabel btnAjustConfig;
    private javax.swing.JLabel btnAjustConfig2;
    private javax.swing.JLabel btnCancelSell;
    private javax.swing.JLabel btnCancelSell1;
    private javax.swing.JLabel btnCancelSell2;
    private javax.swing.JLabel btnCustomersSell;
    private javax.swing.JLabel btnDoSell;
    private javax.swing.JLabel btnDownloadsSell;
    private javax.swing.JLabel btnExportExcelSearchSell;
    private javax.swing.JLabel btnExportPDFSearchSell;
    private javax.swing.JLabel btnProductsStock;
    private javax.swing.JLabel btnSearchSearchSell;
    private javax.swing.JLabel btnSearchSell;
    private javax.swing.JLabel btnSincronizeConfig;
    private javax.swing.JLabel btnTestSellSell;
    private com.toedter.calendar.JDateChooser dateFirstSearchSell;
    private com.toedter.calendar.JDateChooser dateFirstSearchSell1;
    private javax.swing.JTextField inputEmailCustomer;
    private javax.swing.JTextField inputNameCustomer;
    private javax.swing.JTextField inputSearchCustomerSell;
    private javax.swing.JTextField inputSearchCustomerSell1;
    private javax.swing.JTextField inputSearchCustomerSell2;
    private javax.swing.JTextField inputSearchItemSell;
    private javax.swing.JTextField inputSearchItemSell1;
    private javax.swing.JTextField inputSearchSell;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPanel panelCustomer;
    private javax.swing.JPanel panelDoSell;
    private javax.swing.JPanel panelProducts;
    private javax.swing.JPanel panelSearchSell;
    private javax.swing.JTable tabCustomer;
    public javax.swing.JTable tabItemCustomerSell;
    public javax.swing.JTable tabItemCustomerSell1;
    private javax.swing.JTable tabItemsSell;
    private javax.swing.JTable tabItemsSell1;
    private javax.swing.JTable tabSearchSell;
    private javax.swing.JLabel titleArticuloSell;
    private javax.swing.JLabel titleArticuloSell1;
    private javax.swing.JLabel titleArticuloSell2;
    private javax.swing.JLabel titleArticuloSell3;
    private javax.swing.JLabel titleAuxSearchSell1;
    private javax.swing.JLabel titleAuxSearchSell2;
    private javax.swing.JLabel titleConfig;
    private javax.swing.JLabel titleCustomerSell;
    private javax.swing.JLabel titleCustomerSell1;
    private javax.swing.JLabel titleCustomerSell2;
    private javax.swing.JLabel titleDateEndSearchSell1;
    private javax.swing.JLabel titleEmailCustomer;
    private javax.swing.JLabel titleFirstSearchSell;
    private javax.swing.JLabel titleMain;
    private javax.swing.JLabel titleNameCustomer;
    private javax.swing.JLabel titleSearchSell;
    private javax.swing.JLabel titleSells;
    private javax.swing.JLabel titleStock;
    private javax.swing.JLabel titleTotalSell;
    private javax.swing.JLabel titleTotalValueSell;
    private javax.swing.JLabel titleWebSite;
    // End of variables declaration//GEN-END:variables
}
